name: iacapp
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs: 
  iac-app-jobs:
    runs-on: ubuntu-latest
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-south-1
    steps:
    - name: Pull the source code from repo
      uses: actions/checkout@v4
    - name: Install CDK package
      run: npm install -g aws-cdk
    - name: Install Dependencies
      run: npm install 
    - name: Build and Synthesize stack
      run: npm run build && cdk bootstrap
    # - name: Deploy stack
    #   run: npx cdk deploy --require-approval never
    - name: Deploy CDK Synthisize stack
      uses: scottbrenner/aws-cdk-action@v1.6.0
      with:
        args: synth --require-approval never
    - name: Print AWS Credentials
      run: |
        echo "Done!"